### DISCUSSION TITLE
GitHub Action

### DISCUSSION THREAD

**Discussion by misilot** [DNSControl/dnscontrol#3634] [Q&A] [answered]
Hello,

I was wondering if anyone has a GitHub Action workflow example where on a PR it will take the preview output and add a comment to the PR with the changes? Ideally, if the PR is updated at all, the previous comment is replaced as well.

Thank you!

**Comment by tlimoncelli** [comment]
I use `thollander/actions-comment-pull-request@v2` for that.  The comment always shows the latest output, with a drop-down menu to show previous comments.

Here's a snippet from my workflow:

```
    -
      if: ${{ !cancelled() }}
      name: Attach Results as PR comment
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: dnscontrol_preview_datacenter_push
        message: |
          <details open><summary>DNSControl Preview Results (DATACENTER)</summary>

          ### DNS Control Preview Results (DATACENTER)

          (Uses runners in the datacenter)

          ```
          ${{ steps.dnscontrol_preview_datacenter.outputs.dnscontrol_results }}
          ```
          </details>
```

**Comment by misilot** [comment]
Thank you that is helpful! I wonder if something has changed where when I used to just do id:value in the preview task I could get the output in the next task. This helps though and I will do some more digging after lunch.

**Comment by misilot** [comment, marked as answer]
Thank you so much! This worked great. Just curious if there is an official GitHub Action for DNS Control? 

```
      - name: Install DNS Control
        uses: gacts/install-dnscontrol@v1

      - name: DNSControl check
        run: dnscontrol check

      - name: DNSControl preview
        id: dnscontrol_preview
        run: |
          dnscontrol_results=$(dnscontrol --no-colors preview --creds creds.github.json)
          # Truncate if too long to avoid GitHub Action comment limits (optional)
          echo "dnscontrol_results<<EOF" >> $GITHUB_OUTPUT
          echo "$dnscontrol_results" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - if: ${{ !cancelled() }}
        name: Attach Results as PR comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: dnscontrol_preview_push
          message: |
            <details open><summary>DNSControl Preview Results</summary>

            ### DNS Control Preview Results

            ```
            ${{ steps.dnscontrol_preview.outputs.dnscontrol_results }}
            ```
            </details>

```

What I ended up with
